dist: trusty
sudo: required
language: scala
scala:
- 2.11.8
script:
# run unit tests and all ITs except the test tagged with TravisIgnore
  - sbt test "it:test-only -- -l TravisIgnore"
jdk:
- oraclejdk8
cache:
  directories:
    - '$HOME/.ivy2/cache'
addons:
  apt:
    sources:
      - mongodb-3.2-precise
    packages:
      - mongodb-org=3.2.14

before_script:
  - sudo service mongod restart
