
sudo: false
language: scala
scala:
- 2.11.8
script:
  - sbt test it:test
jdk:
- oraclejdk8
cache:
  directories:
    - '$HOME/.ivy2/cache'
addons:
  apt:
    source:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server
branches:
  except:
    - master
    
